apps/products/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.products import views as product_views

urlpatterns = [
    url(r'^products/$', login_required(product_views.ProductListView.as_view()), name='product_list'),
    url(r'^products/cat/(?P<cat_id>[\d]+)/$', login_required(product_views.ProductCatListView.as_view()),
        name='product_cat_list'),
    url(r'^products/create/$', login_required(product_views.ProductCreateView.as_view()), name='product_create'),
    url(r'^products/(?P<pk>[\d]+)/$',
        login_required(product_views.ProductDetailView.as_view()), name='product_detail'),
    url(r'^products/(?P<pk>[\d]+)/delete/$',
        login_required(product_views.ProductDeleteView.as_view()), name='product_delete'),
    url(r'^products/(?P<pk>[\d]+)/edit/$',
        login_required(product_views.ProductEditView.as_view()), name='product_edit'),
]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView

from rest_framework.authtoken import views
from rest_framework_swagger.views import get_swagger_view

from apps.restapp.urls import urlpatterns as rest_urlpatterns

api_title = 'Landskap API documentation'
schema_view = get_swagger_view(title=api_title, patterns=rest_urlpatterns, url='/api/v1/')

urlpatterns = [
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^api/v1/', include('apps.restapp.urls', namespace='rest_api_urls')),
    url(r'^api/v1/', schema_view),
]

urlpatterns += [
    url('^$', RedirectView.as_view(url='/cafe/',)),
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'', include('apps.users.urls', namespace='users')),
    url(r'', include('apps.products.urls', namespace='products')),
    url(r'', include('apps.modifiers.urls', namespace='modifiers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]

apps/products/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse

from ckeditor.fields import RichTextField
from autoslug.fields import AutoSlugField
from mptt.models import MPTTModel, TreeForeignKey
from apps.modifiers.models import ModifierCategory

from apps.users.models import Album, File, Cafe


class ProductCategory(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    is_top = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='product/category/', default='default.png')
    available = models.BooleanField(default=False)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Product category'
        verbose_name_plural = 'Product categories'

    def __str__(self):
        return "{}".format(self.name)


class ProductImage(models.Model):
    file = models.FileField(upload_to='album/%y/%m/%d', null=True, blank=True, default='default.png')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')

    class Meta:
        verbose_name = 'Product image'
        verbose_name_plural = 'Product images'


class Product(models.Model):
    image = models.FileField(upload_to='products/%y/%m/%d', null=True, blank=True, default='default.png')
    title = models.CharField(max_length=254)
    description = models.TextField()
    available = models.BooleanField(default=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    slug = AutoSlugField(populate_from='title', unique=True, null=True)
    category = models.ForeignKey(ProductCategory, null=True, blank=True)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    modifier = models.ForeignKey(ModifierCategory, on_delete=models.CASCADE, related_name='meals')

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.pk])


class Size(models.Model):
    title = models.CharField(max_length=254)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product = models.ForeignKey(Product, null=False, blank=True)
    default = models.BooleanField(default=False)
    available = models.BooleanField(default=True)


class CafeMeals(models.Model):
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE, related_name='meals')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='cafes')

    class Meta:
        verbose_name = 'Cafe product'
        verbose_name_plural = 'Cafe products'


class ProductModifier(models.Model):
    modifier = models.ForeignKey(ModifierCategory, on_delete=models.CASCADE, related_name='products')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='modifiers')

    class Meta:
        verbose_name = 'Product modifier'
        verbose_name_plural = 'Product modifiers'

apps/products/forms.py
from django import forms


from apps.products.models import Product, ProductImage


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        exclude = ('order', )


AlbumFormSet = forms.inlineformset_factory(Product, ProductImage,
                                           form=ProductImageForm,
                                           extra=5,
                                           can_order=False,
                                           max_num=5)

apps/products/views.py
from django.views import generic
from django.shortcuts import redirect, reverse, get_object_or_404, Http404
from django.db import transaction

from apps.products import models as product_models
from apps.modifiers import models as modifier_models
from apps.products import forms as product_forms
from apps.users import models as user_models


class ProductListView(generic.ListView):
    template_name = 'pages/products/product_list.html'
    model = product_models.Product
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = product_models.ProductCategory.objects.all()
        return context

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)


class ProductCatListView(generic.ListView):
    template_name = 'pages/products/product_list.html'
    model = product_models.Product
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = product_models.ProductCategory.objects.all()
        return context

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user, category_id=self.kwargs.get('cat_id'))


class ProductDetailView(generic.DetailView):
    template_name = 'pages/products/product_detail.html'
    model = product_models.Product


class ProductCreateView(generic.CreateView):
    template_name = 'pages/products/product_create.html'
    model = product_models.Product
    fields = ['image', 'title', 'description', 'price', 'available', 'category', ]

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['cafes'] = product_models.Cafe.objects.filter(user=self.request.user)
        context['modifiers'] = modifier_models.ModifierCategory.objects.all()

        cafes = self.request.POST.getlist('cafe')
        if cafes:
            context['selected_cafes'] = cafes
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        cafes = self.request.POST.getlist('cafe')
        modifiers = self.request.POST.getlist('modifier')
        with transaction.atomic():
            instance = form.save(commit=False)
            instance.owner = self.request.user
            instance.save()
            self.object = instance

            if modifiers:
                product_modifiers = product_models.ProductModifier.objects.filter(product_id=instance.id)
                if product_modifiers.exists():
                    product_modifiers.delete()
                for modifier in modifiers:
                    product_modifier = product_models.ProductModifier(product_id=instance.id, modifier_id=modifier)
                    product_modifier.save()

            if cafes:
                cafe_meals = product_models.CafeMeals.objects.filter(product_id=instance.id)
                if cafe_meals.exists():
                    cafe_meals.delete()
                for cafe in cafes:
                    cafe_meal = product_models.CafeMeals(cafe_id=cafe, product_id=instance.id)
                    cafe_meal.save()


class ProductDeleteView(generic.DeleteView):
    template_name = 'pages/products/product_delete.html'
    model = product_models.Product

    def get_success_url(self):
        return reverse('products:product_list')


class ProductEditView(generic.UpdateView):
    template_name = 'pages/products/product_edit.html'
    model = product_models.Product
    fields = ['image', 'title', 'description', 'price', 'available', 'category', ]

    def get_context_data(self, **kwargs):
        context = super(ProductEditView, self).get_context_data(**kwargs)
        context['cafes'] = user_models.Cafe.objects.filter(user=self.request.user)
        context['modifiers'] = modifier_models.ModifierCategory.objects.all()

        product_modifiers = product_models.ProductModifier.objects.filter(product_id=self.object.id)
        if product_modifiers.exists():
            context['selected_modifiers'] = product_modifiers.prefetch_related('modifier').values_list('modifier',
                                                                                                       flat=True)

        cafe_meals = product_models.CafeMeals.objects.filter(product_id=self.object.id)
        if cafe_meals.exists():
            context['selected_cafes'] = cafe_meals.prefetch_related('cafe').values_list('cafe', flat=True)
        return context

    def form_valid(self, form):
        print(form.data.get('description'))
        form.save()
        context = self.get_context_data()
        cafes = self.request.POST.getlist('cafe')
        modifiers = self.request.POST.getlist('modifier')
        instance = self.get_object()
        if modifiers:
            product_modifiers = product_models.ProductModifier.objects.filter(product_id=instance.id)
            if product_modifiers.exists():
                product_modifiers.delete()
            for modifier in modifiers:
                product_modifier = product_models.ProductModifier(product_id=instance.id, modifier_id=modifier)
                product_modifier.save()

        if cafes:
            cafe_meals = product_models.CafeMeals.objects.filter(product_id=instance.id)
            if cafe_meals.exists():
                cafe_meals.delete()
            for cafe in cafes:
                cafe_meal = product_models.CafeMeals(cafe_id=cafe, product_id=instance.id)
                cafe_meal.save()
            return super().form_valid(form)

        return super(ProductCreateView, self).form_valid(form)

templates/pages/products/product_create.html
{% extends 'base.html' %}
{% load static i18n widget_tweaks landskap_tags %}


{% block content %}
    <div class="new_cafe container my">
        <span class="span_products_edit">NEW PRODUCT</span>
        <div class="div_products_edit"></div>
    </div>

    <div class="towns container my">
        <div class="row">
            <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                <div class="products_edit_img_block">
                    <div class="products_edit_img_block_inner">
                        <div class="products_edit_img_block_inner_img">
                            <div style="background-image: url({{ product.images.first.file.url }});"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-9 col-md-6 col-sm-12">
                {{ form.errors }}
                <form method="post" action="" class="products_edit_form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="products_edit_left_form">
                        <div>
                            {% render_field form.image class='form-control' %}
                            <div></div>
                        </div>
                        <div>
                            {% render_field form.title placeholder='Title' %}
                            <div></div>
                        </div>
                        <div>
                            {% render_field form.description rows='3' class='form-control' placeholder='Description' %}
                            <div></div>
                        </div>
                        <div>
                            {% render_field form.category placeholder='Category' %}
                        </div>
                        <div>
                            {% render_field form.price placeholder='Price' %}
                            <div></div>
                        </div>
                    </div>
                    <div class="products_edit_right_form">
                        <select name="cafe" id="id_cafe" class="form-control" multiple>
                            {% for cafe in cafes %}
                                <option value="{{ cafe.id }}" {% if product.id|cafe_exist:cafe.id %}selected{% endif %}>
                                    {{ cafe.cafe_name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="products_edit_right_form">
                        <select name="modifier" id="id_modifier" class="form-control" multiple>
                            {% for modifier in modifiers %}
                                <option value="{{ modifier.id }}">
                                    {{ modifier.title }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <button>Remove</button>
                        <button>Cancel</button>
                        <button>Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="all_display"></div>

    <script src="{% static 'JQuery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

{% block css %}
    <style>

    </style>
{% endblock %}

templates/pages/products/product_delete.html
{% extends 'base.html' %}
{% load static i18n %}


{% block content %}
<div class="page-content">
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="{% trans 'Confirm' %}">
    </form>
</div>
{% endblock %}

templates/pages/products/product_detail.html
{% extends 'base.html' %}
{% load static i18n %}


{% block content %}
    <div class="new_cafe container my">
        <span class="span_products">PRODUCTS</span>
        <div class="div_products"></div>
        <a href="{% url 'products:product_create' %}">NEW PRODUCT</a>
    </div>
    <div class="towns container my">
        <div class="product_images col-md-5">
            <img style="width: 100%; height: 100%;" class="product_image" id="img_01" src="{{ object.image.url }}" data-zoom-image="{{ object.image.url }}"/>
        </div>
        <div class="product_text col-md-7">
            <div class="price">
                <strong>Price</strong>: {{ object.price }}
            </div>
            <div class="description">
                {{ object.description|safe }}
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/products/product_edit.html
{% extends 'base.html' %}
{% load static i18n widget_tweaks landskap_tags %}


{% block content %}
    <div class="new_cafe container my">
        <span class="span_products_edit">NEW PRODUCT</span>
        <div class="div_products_edit"></div>
    </div>

    <div class="towns container my">
        <div class="row">
            <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12">
                <div class="products_edit_img_block">
                    <div class="products_edit_img_block_inner">
                        <div class="products_edit_img_block_inner_img">
                            <div style="background-image: url({{ product.image.url }});"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-9 col-lg-9 col-md-6 col-sm-12">
                {{ form.errors }}
                <form method="post" action="" class="products_edit_form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="products_edit_left_form">
                        <div id="product_image_wrapper">
                            {% render_field form.image class='form-control' %}
                            <div></div>
                        </div>
                        <div>
                            {% render_field form.title placeholder='Title' %}
                            <div></div>
                        </div>
                        <div>
                            {% render_field form.description rows='3' class='form-control' placeholder='Description' %}
                            <div></div>
                        </div>
                        <div>
                            {% render_field form.category placeholder='Category' %}
                        </div>
                        <div>
                            {% render_field form.price placeholder='Price' %}
                            <div></div>
                        </div>
                    </div>
                    <div class="products_edit_right_form">
                        <select name="cafe" id="id_cafe" class="form-control" multiple>
                            {% for cafe in cafes %}
                                <option value="{{ cafe.id }}" {% if product.id|cafe_exist:cafe.id %}selected{% endif %}>
                                    {{ cafe.cafe_name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="products_edit_right_form">
                        <select name="modifier" id="id_modifier" class="form-control" multiple>
                            {% for modifier in modifiers %}
                                <option value="{{ modifier.id }}" {% if modifier.id|modifier_exist:product.id %}selected{% endif %}>
                                    {{ modifier.title }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div>
                        <button>Remove</button>
                        <button>Cancel</button>
                        <button>Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="all_display"></div>
    <script src="{% static 'JQuery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

{% block css %}
    <style>
        #product_image_wrapper, #product_image_wrapper::selection {
            color: transparent;
        }

        #product_image_wrapper * {
            display: none;
        }

        #product_image_wrapper input[type=file] {
            display: block;
        }
    </style>
{% endblock %}

templates/pages/products/product_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <div class="new_cafe container my">
        <span class="span_products">PRODUCTS</span>
        <div class="div_products"></div>
        <a href="{% url 'products:product_create' %}">NEW PRODUCT</a>
    </div>

    <div class="towns container my">
        <div class="div_products_table row">
            <ul action="" class="div_products_table_form col-lg-2">
                {% url 'products:product_list' as products_list_url %}
                <li class="{% if request.path == products_list_url %}active{% endif %}"><a href="{{ products_list_url }}">All products</a></li>
                {% for category in categories %}
                    {% url 'products:product_cat_list' cat_id=category.id as product_cat_list_url %}
                    <li class="{% if request.path == product_cat_list_url %}active{% endif %}"><a href="{{ product_cat_list_url }}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
            <table class="products_table col-lg-10">
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Info</th>
                    <th>Status</th>
                    <th>Price</th>
                    <th>Action</th>
                </tr>
                {% for product in product_list %}
                    <tr>
                        <td><img style="width: 81px;" src="{{ product.image.url }}" alt=""></td>
                        <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
                        <td>{% if product.category %}{{ product.category }}{% else %}-{% endif %}</td>
                        <td>
                            <div>
                                <p>{{ product.description|safe }}</p>
                            </div>
                        </td>
                        <td>{% if product.available %}<p>Available</p>{% else %}<p>Not available</p>{% endif %}</td>
                        <td>{{ product.price }}</td>
                        <td><a href="{% url 'products:product_edit' pk=product.pk %}">Edit</a>
                            <a href="{% url 'products:product_delete' pk=product.pk %}">Remove</a></td>
                    </tr>
                {% endfor %}
            </table>
            {% if is_paginated %}
                <div class="products_buttons col-12">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-dark">Prev</a>
                    {% endif %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-dark">Next</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>

    </div>

    <nav class="nav nav_fixed">
        <div class="user">
            <div class="user_img">
                <img src="{% static 'img/logo_3.jpg' %}" alt="">
            </div>
            <div class="user_name">
                <p>John Martin</p>
                <span>Manager</span>
            </div>
        </div>
        <ul>
            <li class="active"><a href="#">My Cafes</a></li>
            <li><a href="#">Employees</a></li>
            <li><a href="#">Products</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Settings</a></li>
        </ul>
        <a class="login_out" href="#">
            <img src="{% static 'img/login_out-512.png' %}" alt="">Log out
        </a>
    </nav>

    <div class="all_display"></div>

    <script src="{% static 'JQuery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}