apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from apps.users import views as user_views


urlpatterns = [
    url(r'^login/$', user_views.LoginView.as_view(), name='login_page'),
    url(r'^register/$', user_views.RegisterView.as_view(), name='register_page'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/'}, name='logout',),
    url(r'^settings/$', login_required(user_views.ProfileView.as_view()), name='settings'),

    url(r'^settings/password/$', login_required(user_views.ProfilePasswordView.as_view()),
        name='profile_password_page'),
    url(r'^notifications/$', login_required(user_views.NotificationsView.as_view()), name='company_notifications'),
    url(r'^notifications/(?P<pk>[\d]+)$', login_required(user_views.NotificationDetailView.as_view()),
        name='company_notifications_detail'),


    url(r'^news/$', login_required(user_views.NewsListView.as_view()), name='news_list'),
    url(r'^news/create/$', login_required(user_views.NewsCreateView.as_view()), name='news_create'),
    url(r'^news/(?P<pk>[\d]+)/$', login_required(user_views.NewsDetailView.as_view()), name='news_detail'),
    url(r'^news/(?P<pk>[\d]+)/delete/$', login_required(user_views.NewsDeleteView.as_view()), name='news_delete'),
    url(r'^news/(?P<pk>[\d]+)/edit/$', login_required(user_views.NewsEditView.as_view()), name='news_edit'),

    url(r'^password/reset/$', user_views.PasswordResetView.as_view(), name='password_reset', ),
    url(r'^password/done/$', user_views.PasswordResetDoneView.as_view(), name='password_reset_done', ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    url(r'^reset/done/$', user_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^cafe/$', login_required(user_views.CafeListView.as_view()), name='cafe_list'),
    url(r'^cafe/add/$', login_required(user_views.CafeAddView.as_view()), name='cafe_add'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/$', login_required(user_views.CafeDetailView.as_view()), name='cafe_detail'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/edit/$', login_required(user_views.CafeEditView.as_view()), name='cafe_edit'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/delete/$', login_required(user_views.CafeDeleteView.as_view()), name='cafe_delete'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/work-time/$', login_required(user_views.CafeWeekTimeView.as_view()),
        name='cafe_week_time_page'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/location/$', login_required(user_views.CafeLocationView.as_view()),
        name='cafe_location_page'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/$', login_required(user_views.GalleryView.as_view()), name='cafe_gallery'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/add/$', login_required(user_views.GalleryAddView.as_view()),
        name='cafe_gallery_add'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/(?P<file_id>[\d]+)/delete/$',
        login_required(user_views.GalleryDeleteView.as_view()), name='cafe_gallery_delete'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/reviews/$', login_required(user_views.CafeReviewsView.as_view()),
        name='cafe_review_list'),

    url(r'^employees/$', login_required(user_views.EmployeesView.as_view()), name='employee_list'),
    url(r'^employees/(?P<employee_id>[\d]+)/$', login_required(user_views.EmployeeEditView.as_view()),
        name='employee_edit'),
    url(r'^employees/(?P<employee_id>[\d]+)/password/$', login_required(user_views.EmployeePasswordView.as_view()),
        name='employee_password'),
    url(r'^employees/(?P<employee_id>[\d]+)/delete/$', login_required(user_views.EmployeeDeleteView.as_view()),
        name='employee_delete'),
    url(r'^employees/add/$', login_required(user_views.EmployeeAddView.as_view()), name='employee_add'),
    url(r'^employees/add/existing/$', login_required(user_views.EmployeeAddExistingView.as_view()),
        name='employee_add_existing'),
    url(r'^transactions/$', user_views.TransactionsListView.as_view(), name='transactions_list'),
    url(r'^transactions/(?P<uuid>[0-9A-Za-z\-]+)/$', user_views.TransactionDetailView.as_view(),
        name='transaction_detail'),
]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView

from rest_framework.authtoken import views
from rest_framework_swagger.views import get_swagger_view

from apps.restapp.urls import urlpatterns as rest_urlpatterns

api_title = 'Landskap API documentation'
schema_view = get_swagger_view(title=api_title, patterns=rest_urlpatterns, url='/api/v1/')

urlpatterns = [
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^api/v1/', include('apps.restapp.urls', namespace='rest_api_urls')),
    url(r'^api/v1/', schema_view),
]

urlpatterns += [
    url('^$', RedirectView.as_view(url='/cafe/',)),
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'', include('apps.users.urls', namespace='users')),
    url(r'', include('apps.products.urls', namespace='products')),
    url(r'', include('apps.modifiers.urls', namespace='modifiers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]

apps/payment/models.py
from django.db import models
from django.db.models.signals import post_save

from apps.orders import models as order_models


class StripeTransaction(models.Model):

    payer = models.ForeignKey('users.User')
    created_at = models.DateTimeField(auto_now=True)
    token = models.CharField(max_length=254, null=True)
    customer_id = models.CharField(max_length=254, null=True)
    card_id = models.CharField(max_length=254, null=True)
    amount = models.FloatField()
    payment_id = models.CharField(max_length=254)
    description = models.TextField()
    order = models.ForeignKey('orders.Order')
    payment_type = models.CharField(max_length=254)
    payment_time = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=60, null=True, default='in_process')


def stripe_saver(sender, instance, **kwargs):
    if kwargs['created']:
        order_models.Transaction.objects.create(order=instance.order,
                                                payment_type=instance.payment_type,
                                                amount=instance.amount,
                                                payer=instance.payer)


post_save.connect(sender=StripeTransaction, receiver=stripe_saver)


class PaypalTransaction(models.Model):
    transaction_id = models.TextField(editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField()
    description = models.TextField(null=True, blank=True)
    order = models.ForeignKey('orders.Order')
    payment_type = models.CharField(max_length=254)
    payment_time = models.DateTimeField(auto_now_add=True)

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os

from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.shortcuts import reverse
from django.db.models.signals import post_save
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor.fields import RichTextField
from geosimple.fields import GeohashField
from autoslug.fields import AutoSlugField
from localflavor.us.models import USStateField

from project import tasks as project_tasks
from project import modules as project_modules

from .managers import (
    CafeManager,
    AlbumManager,
)


GENDERS = (
    ('male', _('Male')),
    ('female', _('Female')),
)

WEEK_DAYS = (
    ('monday', _('Monday'),),
    ('tuesday', _('Tuesday'),),
    ('wednesday', _('Wednesday'),),
    ('thursday', _('Thursday'),),
    ('friday', _('Friday'),),
    ('saturday', _('Saturday'),),
    ('sunday', _('Sunday'),),
)


def get_week_day(day):
    for key, week_day in enumerate(WEEK_DAYS):
        if key == day:
            return week_day[0]
    return None


class Album(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_created=True, auto_now_add=True, auto_now=False, editable=True)
    updated_at = models.DateTimeField(auto_created=True, auto_now_add=False, auto_now=True, editable=True)
    cafe = models.ForeignKey('Cafe', on_delete=models.CASCADE, null=True, blank=True)

    def get_files(self, obj):
        return File.objects.filter(album=self)

    def __str__(self):
        return "Album - {}".format(self.id)

    objects = AlbumManager()


class File(models.Model):
    file = models.FileField(upload_to='album/%y/%m/%d', null=True, blank=True, default='default.png')
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    def is_image(self):
        if self.extension().lower() in ['.png', '.jpg', '.jpeg']:
            return True
        return False


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, phone, password, **extra_fields):
        user = self.model(phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(phone, password, **extra_fields)

    def create_superuser(self, phone, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(phone, password, **extra_fields)


class CafeOwnerManager(BaseUserManager):

    def get_queryset(self):
        return super().get_queryset().filter(user_type=User.OWNER)


class User(AbstractUser):
    OWNER = 1
    USER = 2
    USER_TYPE_CHOICES = (
        (OWNER, _('Cafe owner')),
        (USER, _('Simple user')),
    )
    username = models.CharField(max_length=12, null=True, blank=True)
    phone = models.CharField(max_length=12, unique=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=USER)
    first_name = models.CharField(_('First name'), max_length=30, blank=True)
    last_name = models.CharField(_('Last name'), max_length=30, blank=True)
    date_joined = models.DateTimeField(_('Date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('Active'), default=True)
    date_of_birthday = models.DateField(_('date of birthday'), null=True, blank=True, )
    gender = models.CharField(choices=GENDERS, max_length=6, null=True, blank=True, )
    avatar = models.ImageField(null=True, default='default.png')
    referral_code = models.CharField(max_length=60, null=True, blank=True)
    is_can_reject = models.BooleanField(_('Reject'), default=False)
    USERNAME_FIELD = 'phone'
    objects = UserManager()
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.phone

    def get_avatar(self, request):
        return request.build_absolute_uri(self.avatar.url)

    @property
    def is_cashier(self):
        return Cashier.objects.filter(cashier=self).count()

    def set_referral_code(self):
        self.referral_code = "{:06}".format(self.pk)


class SocialProfile(models.Model):
    FACEBOOK = 'facebook'
    GOOGLE = 'google'
    PROVIDERS = (
        (FACEBOOK, 'Facebook'),
        (GOOGLE, 'Google'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='social_profile')
    provider = models.CharField(choices=PROVIDERS, max_length=60)
    social_user_id = models.CharField(max_length=254)
    token = models.TextField()


class CafeOwner(User):
    objects = CafeOwnerManager()

    class Meta:
        proxy = True


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    is_top = models.BooleanField(default=False)
    icon = models.ImageField(upload_to='category/', default='default.png')
    svg_icon = models.FileField(upload_to='category/', default='default.png')

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return "{}".format(self.name)


class WeekTime(models.Model):
    day = models.CharField(choices=WEEK_DAYS, max_length=15,)
    opening_time = models.TimeField(null=True, blank=True)
    closing_time = models.TimeField(null=True, blank=True)
    is_default = models.BooleanField(default=False)
    cafe = models.ForeignKey('Cafe', null=True, related_name='week_time')

    def __str__(self):
        return self.day


class Cafe(models.Model):
    BLOCKED = 0
    ACTIVE = 1
    PENDING = 2
    STATUS = (
        (BLOCKED, _('Blocked')),
        (ACTIVE, _('Active')),
        (PENDING, _('Pending')),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name='cafe_owner',
                             verbose_name=_('Cafe owner'))
    cafe_name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='cafe_category')
    description = RichTextField()
    call_center = models.CharField(max_length=13, verbose_name='Phone')
    website = models.URLField(null=True, blank=True)
    status = models.IntegerField(choices=STATUS, default=BLOCKED)
    location = GeohashField(default={'latitude': 50.822482, 'longitude': -0.141449}, editable=False)
    address = models.TextField(null=True, blank=True, verbose_name=_('Address 1'))
    second_address = models.TextField(null=True, blank=True, verbose_name=_('Address 2'))
    city = models.CharField(null=True, blank=True, max_length=220)
    state = USStateField(null=True)
    postal_code = models.CharField(null=True, max_length=12)
    tax_rate = models.DecimalField(max_digits=100, decimal_places=2)

    objects = CafeManager()

    def __str__(self):
        return self.cafe_name

    @property
    def get_total_rate(self):
        total_rate = 0
        rates = Review.objects.filter(cafe=self).values('rate')
        if len(rates) > 0:
            for rate in rates:
                total_rate += rate['rate']
            total_rate = total_rate / len(rates)
        return total_rate

    @property
    def get_likes(self):
        likes = Review.objects.filter(cafe=self, rate=1).count()
        return likes

    @property
    def get_dislikes(self):
        dislikes = Review.objects.filter(cafe=self, rate=-1).count()
        return dislikes

    def cafe_changed(self):
        self.status = self.PENDING
        self.save()

    def get_time_graphic(self):
        return self.week_time.values('day', 'opening_time', 'closing_time', )

    def get_absolute_url(self):
        return reverse('users:cafe_detail', args=[self.pk])

    @property
    def logo(self):
        return self.user.settings.logo


# Todo: CafeGeneralSettings must be auto generated on cafe_owner created
class CafeGeneralSettings(models.Model):
    owner = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='settings')
    cafe_name = models.CharField(max_length=120, null=True, blank=True)
    exchangeable_product = models.ForeignKey('products.ProductCategory', null=True, blank=True)
    exchangeable_point = models.IntegerField(default=10)
    expiration_days = models.IntegerField(default=30)
    show_reviews = models.BooleanField(default=True)
    logo = models.ImageField(null=True)

    def __str__(self):
        return self.cafe_name or "--empty--"

    class Meta:
        verbose_name = 'Cafe general setting'
        verbose_name_plural = 'Cafe general settings'


class Cashier(models.Model):
    cafe = models.ForeignKey(Cafe, related_name='cafe_cashiers')
    cashier = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='cashiers')

    def __str__(self):
        return "Cafe - {}, Cashier - {}".format(self.cafe.cafe_name, self.cashier)


class Review(MPTTModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='review_author')
    parent = TreeForeignKey('self', null=True, blank=True, related_name='review_parent', db_index=True)
    comment = models.TextField()

apps/payment/views.py
from django.shortcuts import render

# Create your views here.

templates/pages/login.html
{% extends 'login_base.html' %}
{% load static i18n %}

{% block title %}Login{% endblock %}

{% block content %}
        <div class="left_login_block" style="background-image:url({% static 'img/login_left_img.png' %});"></div>
        <div class="right_login_block">
            <div class="right_login_block_inner">
                <div class="logo_login">
                   <img src="{% static 'img/logo_invert.png' %}" alt="">
                </div>
                <form class="login_form" action="{% url 'users:login_page' %}" method="post">
                    <div>
                        <label>
                            <img src="{% static 'img/person_icon.png' %}" alt=""><span>+998</span>
                        </label>
                        <input
                            type="text"
                            name="{{ form.username.name }}"
                            placeholder="991112233"
                            pattern="[0-9]{9}"
                            size="9"
                            maxlength="9"
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        >
                        {% if form.username.errors %}
                            <div class="text-danger">
                                {{ form.username.errors }}
                            </div>
                        {% endif %}

                    </div>
                    <div>
                        <img src="{% static 'img/login_password.png' %}" alt="">
                        <input type="password" name="{{ form.passwd.name }}" placeholder="{% trans 'Password' %}">
                        {% if form.passwd.errors %}
                            <div class="text-danger">
                                {{ form.passwd.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div>
                        <p>
                            <input type="checkbox" value="remember" id="remember">
                            <label for="remember">Remember me</label>
                        </p>
                        <a href="{% url 'users:password_reset' %}">Forgot password</a>
                    </div>
                    <div>
                        <button>login</button>
                        <button>sign up</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>
{% endblock %}

templates/pages/notifications.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Dashboard' %}{% endblock %}

{% block content %}
    <section class="wrapper">
        {% include 'parts/main_header.html' %}
        <section class="content">
            Company notifications
        </section>
    </section>
{% endblock %}

templates/pages/reviews.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <section class="wrapper">
        {% include 'parts/main_header.html' %}
        <section class="content">
            <div class="dashboard">
                <div class="dashboard_title">
                    <div class="container">
                        <div class="row">
                            <h2>
                                {% trans 'Dashboard' %}
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="dashboard_content">
                    <div class="container">
                        <div class="row">
                            <div>
                                <div class="col-sm-3">
                                    <h3>{% trans 'New reviews' %}</h3>
                                    <span>{% trans 'last 7 days' %}</span>
                                    <p data-count="{{ new_reviews_within_week }}" class="counter">
                                        {{ new_reviews_within_week }}
                                    </p>
                                </div>
                                <div class="col-sm-3">
                                    <h3>{% trans 'Responded reviews' %}</h3>
                                    <span>{% trans 'last 7 days' %}</span>
                                    <p data-count="{{ responded_reviews_within_week }}" class="counter">
                                        {{ responded_reviews_within_week }}
                                    </p>
                                </div>
                                <div class="col-sm-3">
                                    <h3>{% trans 'Unresponded reviews' %}</h3>
                                    <span>{% trans 'last 7 days' %}</span>
                                    <p data-count="{{ un_responded_reviews_within_week }}" class="counter">
                                        {{ un_responded_reviews_within_week }}
                                    </p>
                                </div>
                                <div class="col-sm-3">
                                    <h3>{% trans 'Total reviews' %}</h3>
                                    <span>{% trans 'last 7 days' %}</span>
                                    <p data-count="{{ total_reviews_within_week }}" class="counter">
                                        {{ total_reviews_within_week }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="reviews">
                <div class="container">
                    <div class="row">
                        <div class="reviews-title">
                            <h3>{{ title }}</h3>
                        </div>
                        <div class="reviews-content">
                            <ul class="nav nav-tabs" role="tablist">
                                {% url 'main:reviews' review_type='latest' as latest_responded_reviews_url %}
                                <li role="presentation" class="{% ifequal request.path latest_responded_reviews_url %}active{% endifequal %}">
                                    <a href="{{ latest_responded_reviews_url }}">
                                        {% trans 'Latest' %}
                                    </a>
                                </li>
                                {% url 'main:reviews' review_type='responded'  as home_responded_reviews_url %}
                                <li role="presentation" class="{% ifequal request.path home_responded_reviews_url %}active{% endifequal %}">
                                   <a href="{{ home_responded_reviews_url }}" >
                                        {% trans 'Responded' %}
                                    </a>
                                </li>
                                {% url 'main:reviews' review_type='not-responded'  as home_not_responded_reviews_url %}
                                <li role="presentation" class="{% ifequal request.path home_not_responded_reviews_url %}active{% endifequal %}">
                                    <a href="{{ home_not_responded_reviews_url }}" >
                                        {% trans 'Not Responded' %}
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div role="tabpanel" class="chats tab-pane active" id="latest">
                                    {% for review in review_list %}
                                        <div class="chats-content" id="review-{{ review.id }}">
                                            <h4>{{ review.author.get_full_name }} <span class="ful-star"></span></h4>
                                            <span>{{ review.created_at|timesince }}</span>
                                            <p>
                                                {{ review.comment }}
                                                {% if review.album.file_set %}
                                                    {% for review_file in review.album.file_set.all %}
                                                        {% if review_file.file %}
                                                            <p><a target="_blank" href="{{ review_file.file.url }}">Attachment</a></p>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endif %}
                                            </p>
                                            {% if review.get_children %}
                                                <div class="answers">
                                                    {% for review_child in review.get_children %}
                                                        <div class="answers-item">
                                                            <div class="answers-profile">
                                                                <div class="answers-profile-img">
                                                                    {% if review_child.author.get_image %}
                                                                        <img src="{{ review_child.author.get_image }}" alt="">
                                                                    {% endif %}
                                                                </div>
                                                                <p class="online">
                                                                    {% if review_child.author.is_authenticated %}
                                                                        online
                                                                    {% else %}
                                                                        offline
                                                                    {% endif %}
                                                                </p>
                                                            </div>
                                                            <div class="answers-text">
                                                                <p>{{ review_child.comment }}</p>
                                                            </div>
                                                        </div>
                                                    {% endfor %}
                                                </div>
                                            {% endif %}

                                            {% if not review.get_children %}
                                                <form action="{{ request.get_full_path }}#review-{{ review.id }}" method="post">
                                                    {% csrf_token %}
                                                    <input name="parent" type="hidden" value="{{ review.id }}">
                                                    <textarea required class="chats-area" name="comment" id=""></textarea>
                                                    <button type="submit" >Reply</button>
                                                </form>
                                            {% endif %}
                                        </div>
                                    {% empty %}
                                        <div class="no_reviews">There are no reviews yet</div>
                                    {% endfor %}
                                </div>
                            </div>
                            {% include 'parts/paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}
{% block css %}
    <style>
        .no_reviews
        {
            margin: 0;
            font-size: 18px;
            font-weight: normal;
            color: #42425c;
            padding: 0px 0 5px 32px;
            letter-spacing: 2px;
        }
    </style>
{% endblock %}