apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from apps.users import views as user_views


urlpatterns = [
    url(r'^login/$', user_views.LoginView.as_view(), name='login_page'),
    url(r'^register/$', user_views.RegisterView.as_view(), name='register_page'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/'}, name='logout',),
    url(r'^settings/$', login_required(user_views.ProfileView.as_view()), name='settings'),

    url(r'^settings/password/$', login_required(user_views.ProfilePasswordView.as_view()),
        name='profile_password_page'),
    url(r'^notifications/$', login_required(user_views.NotificationsView.as_view()), name='company_notifications'),
    url(r'^notifications/(?P<pk>[\d]+)$', login_required(user_views.NotificationDetailView.as_view()),
        name='company_notifications_detail'),


    url(r'^news/$', login_required(user_views.NewsListView.as_view()), name='news_list'),
    url(r'^news/create/$', login_required(user_views.NewsCreateView.as_view()), name='news_create'),
    url(r'^news/(?P<pk>[\d]+)/$', login_required(user_views.NewsDetailView.as_view()), name='news_detail'),
    url(r'^news/(?P<pk>[\d]+)/delete/$', login_required(user_views.NewsDeleteView.as_view()), name='news_delete'),
    url(r'^news/(?P<pk>[\d]+)/edit/$', login_required(user_views.NewsEditView.as_view()), name='news_edit'),

    url(r'^password/reset/$', user_views.PasswordResetView.as_view(), name='password_reset', ),
    url(r'^password/done/$', user_views.PasswordResetDoneView.as_view(), name='password_reset_done', ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    url(r'^reset/done/$', user_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^cafe/$', login_required(user_views.CafeListView.as_view()), name='cafe_list'),
    url(r'^cafe/add/$', login_required(user_views.CafeAddView.as_view()), name='cafe_add'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/$', login_required(user_views.CafeDetailView.as_view()), name='cafe_detail'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/edit/$', login_required(user_views.CafeEditView.as_view()), name='cafe_edit'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/delete/$', login_required(user_views.CafeDeleteView.as_view()), name='cafe_delete'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/work-time/$', login_required(user_views.CafeWeekTimeView.as_view()),
        name='cafe_week_time_page'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/location/$', login_required(user_views.CafeLocationView.as_view()),
        name='cafe_location_page'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/$', login_required(user_views.GalleryView.as_view()), name='cafe_gallery'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/add/$', login_required(user_views.GalleryAddView.as_view()),
        name='cafe_gallery_add'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/(?P<file_id>[\d]+)/delete/$',
        login_required(user_views.GalleryDeleteView.as_view()), name='cafe_gallery_delete'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/reviews/$', login_required(user_views.CafeReviewsView.as_view()),
        name='cafe_review_list'),

    url(r'^employees/$', login_required(user_views.EmployeesView.as_view()), name='employee_list'),
    url(r'^employees/(?P<employee_id>[\d]+)/$', login_required(user_views.EmployeeEditView.as_view()),
        name='employee_edit'),
    url(r'^employees/(?P<employee_id>[\d]+)/password/$', login_required(user_views.EmployeePasswordView.as_view()),
        name='employee_password'),
    url(r'^employees/(?P<employee_id>[\d]+)/delete/$', login_required(user_views.EmployeeDeleteView.as_view()),
        name='employee_delete'),
    url(r'^employees/add/$', login_required(user_views.EmployeeAddView.as_view()), name='employee_add'),
    url(r'^employees/add/existing/$', login_required(user_views.EmployeeAddExistingView.as_view()),
        name='employee_add_existing'),
    url(r'^transactions/$', user_views.TransactionsListView.as_view(), name='transactions_list'),
    url(r'^transactions/(?P<uuid>[0-9A-Za-z\-]+)/$', user_views.TransactionDetailView.as_view(),
        name='transaction_detail'),
]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView

from rest_framework.authtoken import views
from rest_framework_swagger.views import get_swagger_view

from apps.restapp.urls import urlpatterns as rest_urlpatterns

api_title = 'Landskap API documentation'
schema_view = get_swagger_view(title=api_title, patterns=rest_urlpatterns, url='/api/v1/')

urlpatterns = [
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^api/v1/', include('apps.restapp.urls', namespace='rest_api_urls')),
    url(r'^api/v1/', schema_view),
]

urlpatterns += [
    url('^$', RedirectView.as_view(url='/cafe/',)),
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'', include('apps.users.urls', namespace='users')),
    url(r'', include('apps.products.urls', namespace='products')),
    url(r'', include('apps.modifiers.urls', namespace='modifiers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]

templates/pages/accounts/password/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    Landskap | Password reset
{% endblock %}

{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

templates/pages/accounts/password/password_change_form.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
Landskap | Password change
{% endblock %}

{% block content %}
<div id="content-main">

<form method="post">
    {% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {% if form.new_password1.help_text %}
    <div class="help">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {% if form.new_password2.help_text %}
    <div class="help">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="default" />
</div>

</div>
</form></div>

{% endblock %}

templates/pages/accounts/password/password_reset.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Landskap | Forgot Password
{% endblock %}

{% block content %}
    <div class="globalWrapper">
        <section class="formLeft col-sm-6">
            <div class="formLeftImg">
                <img src="{% static 'images/city.jpg' %}" al="">
            </div>
            <div class="leftTitle">
                <h1>Forgot Password</h1>
            </div>
        </section>
        <section class="formRight col-sm-6">
            <div class="logo">
                <img src="{% static 'images/Logo.png' %}" alt="">
            </div>
            <div class="formTitle">
                <h3>Forgot</h3>
                <p>Enter your email and we send you a password reset link</p>
            </div>
            <form class="forgotPass" method="post">
                {% csrf_token %}

                <div class="form-item">
                    <input type="email" name="{{ form.email.name }}" placeholder="Email">
                    {% if form.email.errors %}
                        {{ form.email.errors }}
                    {% endif %}
                </div>
                <div class="form-actions">
                    <input type="submit" name="" value="Send request">
                    <a href="{% url 'users:login_page' %}" class="btn buttons">Back to login</a>
                </div>
            </form>
        </section>
    </div>
{% endblock %}

templates/pages/accounts/password/password_reset_complete.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
Landskap | Password reset complete
{% endblock %}

{% block content %}
<div class="globalWrapper">
    <section class="formLeft col-sm-6">
        <div class="formLeftImg">
            <img src="{% static 'images/city.jpg' %}" al="">
        </div>
        <div class="leftTitle">
            <h1>Password reset complete</h1>
        </div>
    </section>
    <section class="formRight col-sm-6">
        <div class="logo">
            <img src="{% static 'images/Logo.png' %}" alt="">
        </div>
        <div class="formTitle">
            <h3>Password reset complete</h3>
            <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
        </div>
        <p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>
    </section>
</div>
{% endblock %}

templates/pages/accounts/password/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
Landskap | Password reset confirm
{% endblock %}

{% block content %}
<div class="globalWrapper">
    <section class="formLeft col-sm-6">
        <div class="formLeftImg">
            <img src="{% static 'images/city.jpg' %}" al="">
        </div>
        <div class="leftTitle">
            <h1>Password reset confirm</h1>
        </div>
    </section>
    <section class="formRight col-sm-6">
        <div class="logo">
            <img src="{% static 'images/Logo.png' %}" alt="">
        </div>
        {% if validlink %}
            <div class="formTitle">
                <h3>Password reset</h3>
                <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
            </div>
            <form method="post">{% csrf_token %}
                <fieldset class="module aligned">
                    <div class="form-row field-password1 form-item">
                        {{ form.new_password1.errors }}
                        <label for="id_new_password1">{% trans 'New password:' %}</label>
                        {{ form.new_password1 }}
                    </div>
                    <div class="form-row field-password2 form-item">
                        {{ form.new_password2.errors }}
                        <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
                        {{ form.new_password2 }}
                    </div>
                    <div class="form-actions">
                        <input type="submit" value="{% trans 'Change my password' %}"  />
                    </div>
                </fieldset>
            </form>
        {% else %}
            <div class="formTitle">
                <h3>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</h3>
            </div>
        {% endif %}
    </section>
</div>
{% endblock %}
{% block css %}
    <style>
    .form-row ul.errorlist {
        text-align: left;
        margin-left: 20%;
    }
    </style>
{% endblock %}

templates/pages/accounts/password/password_reset_done.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
Landskap | Password reset
{% endblock %}

{% block content %}
<div class="globalWrapper">
    <section class="formLeft col-sm-6">
        <div class="formLeftImg">
            <img src="{% static 'images/city.jpg' %}" al="">
        </div>
        <div class="leftTitle">
            <h1>Password reset</h1>
        </div>
    </section>
    <section class="formRight col-sm-6">
        <div class="logo">
            <img src="{% static 'images/Logo.png' %}" alt="">
        </div>
        <div class="formTitle">
            <h3>Password reset done</h3>
            <p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>
        <p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
        </div>
    </section>
</div>



{% endblock %}

templates/pages/accounts/password/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

templates/pages/accounts/password/password_reset_form.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
Landskap | Password reset
{% endblock %}

{% block content %}

<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-email">
        {{ form.email.errors }}
        <label for="id_email">{% trans 'Email address:' %}</label>
        {{ form.email }}
    </div>
    <input type="submit" value="{% trans 'Reset my password' %}" />
</fieldset>
</form>

{% endblock %}