apps/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from apps.users import views as user_views


urlpatterns = [
    url(r'^login/$', user_views.LoginView.as_view(), name='login_page'),
    url(r'^register/$', user_views.RegisterView.as_view(), name='register_page'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/'}, name='logout',),
    url(r'^settings/$', login_required(user_views.ProfileView.as_view()), name='settings'),

    url(r'^settings/password/$', login_required(user_views.ProfilePasswordView.as_view()),
        name='profile_password_page'),
    url(r'^notifications/$', login_required(user_views.NotificationsView.as_view()), name='company_notifications'),
    url(r'^notifications/(?P<pk>[\d]+)$', login_required(user_views.NotificationDetailView.as_view()),
        name='company_notifications_detail'),


    url(r'^news/$', login_required(user_views.NewsListView.as_view()), name='news_list'),
    url(r'^news/create/$', login_required(user_views.NewsCreateView.as_view()), name='news_create'),
    url(r'^news/(?P<pk>[\d]+)/$', login_required(user_views.NewsDetailView.as_view()), name='news_detail'),
    url(r'^news/(?P<pk>[\d]+)/delete/$', login_required(user_views.NewsDeleteView.as_view()), name='news_delete'),
    url(r'^news/(?P<pk>[\d]+)/edit/$', login_required(user_views.NewsEditView.as_view()), name='news_edit'),

    url(r'^password/reset/$', user_views.PasswordResetView.as_view(), name='password_reset', ),
    url(r'^password/done/$', user_views.PasswordResetDoneView.as_view(), name='password_reset_done', ),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        user_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    url(r'^reset/done/$', user_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^cafe/$', login_required(user_views.CafeListView.as_view()), name='cafe_list'),
    url(r'^cafe/add/$', login_required(user_views.CafeAddView.as_view()), name='cafe_add'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/$', login_required(user_views.CafeDetailView.as_view()), name='cafe_detail'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/edit/$', login_required(user_views.CafeEditView.as_view()), name='cafe_edit'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/delete/$', login_required(user_views.CafeDeleteView.as_view()), name='cafe_delete'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/work-time/$', login_required(user_views.CafeWeekTimeView.as_view()),
        name='cafe_week_time_page'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/location/$', login_required(user_views.CafeLocationView.as_view()),
        name='cafe_location_page'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/$', login_required(user_views.GalleryView.as_view()), name='cafe_gallery'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/add/$', login_required(user_views.GalleryAddView.as_view()),
        name='cafe_gallery_add'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/gallery/(?P<file_id>[\d]+)/delete/$',
        login_required(user_views.GalleryDeleteView.as_view()), name='cafe_gallery_delete'),
    url(r'^cafe/(?P<cafe_id>[\d]+)/reviews/$', login_required(user_views.CafeReviewsView.as_view()),
        name='cafe_review_list'),

    url(r'^employees/$', login_required(user_views.EmployeesView.as_view()), name='employee_list'),
    url(r'^employees/(?P<employee_id>[\d]+)/$', login_required(user_views.EmployeeEditView.as_view()),
        name='employee_edit'),
    url(r'^employees/(?P<employee_id>[\d]+)/password/$', login_required(user_views.EmployeePasswordView.as_view()),
        name='employee_password'),
    url(r'^employees/(?P<employee_id>[\d]+)/delete/$', login_required(user_views.EmployeeDeleteView.as_view()),
        name='employee_delete'),
    url(r'^employees/add/$', login_required(user_views.EmployeeAddView.as_view()), name='employee_add'),
    url(r'^employees/add/existing/$', login_required(user_views.EmployeeAddExistingView.as_view()),
        name='employee_add_existing'),
    url(r'^transactions/$', user_views.TransactionsListView.as_view(), name='transactions_list'),
    url(r'^transactions/(?P<uuid>[0-9A-Za-z\-]+)/$', user_views.TransactionDetailView.as_view(),
        name='transaction_detail'),
]

project/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView

from rest_framework.authtoken import views
from rest_framework_swagger.views import get_swagger_view

from apps.restapp.urls import urlpatterns as rest_urlpatterns

api_title = 'Landskap API documentation'
schema_view = get_swagger_view(title=api_title, patterns=rest_urlpatterns, url='/api/v1/')

urlpatterns = [
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^api/v1/', include('apps.restapp.urls', namespace='rest_api_urls')),
    url(r'^api/v1/', schema_view),
]

urlpatterns += [
    url('^$', RedirectView.as_view(url='/cafe/',)),
    url(r'^admin/', admin.site.urls),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'', include('apps.users.urls', namespace='users')),
    url(r'', include('apps.products.urls', namespace='products')),
    url(r'', include('apps.modifiers.urls', namespace='modifiers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]

templates/pages/news/news_create.html
{% extends 'base.html' %}
{% load static i18n widget_tweaks %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div class="new_cafe container my">
        <span class="span_products_edit">CREATE NEWS</span>
        <div class="div_products_edit"></div>
    </div>
    <div class="towns container my">
        <div class="row">
            {{form.media}}
            <div class="page-content">
                <div class="col-md-9">
                    {% include 'parts/form-template.html' %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/news/news_delete.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div class="new_cafe container my">
        <span class="span_products_edit">NEWS DELETE</span>
        <div class="div_products_edit"></div>
    </div>
    <div class="towns container my">
        <div class="row">
            <div class="page-title">
                <h2>{{ object.title }}</h2>
            </div>
            <div class="page-content">
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-primary" value="{% trans 'Confirm' %}">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/news/news_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div class="new_cafe container my">
        <span class="span_products_edit">{{ object.title }}</span>
        <div class="div_products_edit"></div>
    </div>
    <div class="towns container my">
        <div class="row">
            <div class="page-content">
                {% if object.image %}
                    <div class="news_image col-md-3">
                        <img style="width: 100%; " src="{{ object.image.url }}" alt="">
                    </div>
                {% endif %}
                <div class="news_text col-md-9">
                    {{ object.content|safe }}
                </div>
                <div class="actions">
                    <a href="{% url 'users:news_delete' pk=object.pk %}" class="btn btn-danger pull-right">
                        Delete
                    </a>
                    <a href="{% url 'users:news_edit' pk=object.pk %}" class="btn btn-primary pull-right">
                        Edit
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/pages/news/news_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Dashboard' %}{% endblock %}

{% block content %}
    <div class="new_cafe container my">
        <span class="span_products_edit">{% trans 'News list' %}</span>
        <div class="div_news_edit"></div>
        <a href="{% url 'users:news_create' %}">CREATE NEWS</a>
    </div>
    <div class="towns container my">
        <div class="div_products_table row">
                <table class="news_table">
                    <tr>
                        <th>Picture</th>
                        <th>Title</th>
                        <th>Action</th>
                    </tr>
                    {% for news_item in news_list %}
                        <tr>
                            <td>
                                <a href="{% url 'users:news_edit' pk=news_item.pk %}">
                                    {% if news_item.image %}
                                        <img src="{{ news_item.image.url }}" alt="{{ news_item.title }}">
                                    {% else %}
                                        <img src="{% static 'default.png' %}" alt="">
                                    {% endif %}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'users:news_edit' pk=news_item.pk %}">
                                    {{ news_item.title }}
                                </a>
                            </td>
                            <td class="news_table_actions"><a href="{% url 'users:news_edit' pk=news_item.pk %}">Edit</a>
                                <a href="{% url 'users:news_delete' pk=news_item.pk %}">Remove</a></td>
                        </tr>
                    {% endfor %}
                </table>
                {% if is_paginated %}
                    <div class="products_buttons col-12">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-dark">Prev</a>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-dark">Next</a>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
    </div>

{% endblock %}
{% block css %}
    <style>
        .news_item{
            display: inline-block;
        }
        .news_image img {
            height: 200px;
            width: 100%;
        }
        .news_table td:first-child img
        {
            width: 100%;
        }
        .news_table td:first-child
        {
            width: 10%;
            text-align: center;
        }
    </style>
{% endblock %}